### Teste de webhook Shopify - validação HMAC

# Primeiro, defina a variável SHOPIFY_API_SECRET para o segredo do seu app
@secret=598f2730a0caec9788d24c31838f6272

POST http://localhost:3000/webhooks/orders/create
Content-Type: application/json
x-shopify-hmac-sha256: N3k1p6Sjg5J0B8B1tQ+XZ1Q8TtFzV9oTxqJDx6rCReI=

{
  "id": 12345,
  "email": "customer@example.com",
  "total_price": "100.00",
  "line_items": [
    {
      "name": "Pizza Margherita",
      "quantity": 1,
      "price": "30.00"
    }
  ]
}
